language: go

sudo: required

dist: xenial

matrix:
  include:
    - go: '1.12.x'

env:
  global:
    - DEX_MYSQL_DATABASE=dex
    - DEX_MYSQL_USER=root
    - DEX_MYSQL_HOST="localhost"
    - DEX_MYSQL_PASSWORD=""
    - DEX_POSTGRES_DATABASE=postgres
    - DEX_POSTGRES_USER=postgres
    - DEX_POSTGRES_HOST="localhost"
    - DEX_ETCD_ENDPOINTS=http://localhost:2379
    - DEX_LDAP_TESTS=1
    - DEBIAN_FRONTEND=noninteractive
    - DEX_KEYSTONE_URL=http://localhost:5000
    - DEX_KEYSTONE_ADMIN_URL=http://localhost:35357
    - DEX_KEYSTONE_ADMIN_USER=demo
    - DEX_KEYSTONE_ADMIN_PASS=DEMO_PASS

go_import_path: github.com/dexidp/dex

services:
  - mysql
  - postgresql
  - docker

before_install:
  - mysql -e 'CREATE DATABASE dex;'

install:
  - sudo -E apt-get install -y --force-yes slapd time ldap-utils
  - sudo /etc/init.d/slapd stop
  - docker run -d --net=host gcr.io/etcd-development/etcd:v3.2.9
  - docker run -d -p 0.0.0.0:5000:5000 -p 0.0.0.0:35357:35357 openio/openstack-keystone:pike
  - |
    until curl --fail http://localhost:5000/v3; do
      echo 'Waiting for keystone...'
      sleep 1;
    done;

script:
  - make testall
  - ./scripts/test-k8s.sh
  - make verify-proto # Ensure proto generation doesn't depend on external packages.

notifications:
  email: false
